HubbleSpace_Final-master/HubbleSpace_Final/Controllers/Client_AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HubbleSpace_Final.Entities;
using HubbleSpace_Final.Models;
using HubbleSpace_Final.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HubbleSpace_Final.Controllers
{
    public class Client_AccountsController : Controller
       
    {
        private readonly IAccountRepository _accountRepository;
        private readonly MyDbContext _context;
        public Client_AccountsController(IAccountRepository accountRepository,MyDbContext context)
        {
            _accountRepository = accountRepository;
            _context = context;
        }
       [Route("signup")]
        public IActionResult SignUp()
        {   
            return View();
        }
        [Route("signup")]
        [HttpPost]
        public async Task<IActionResult> SignUp(SignUpUserModel userModel)
        {
            if (ModelState.IsValid)
            {
                var result = await _accountRepository.CreateUserAsync(userModel);
                if (!result.Succeeded)
                {
                    foreach (var errorMessage in result.Errors)
                    {
                        ModelState.AddModelError("", errorMessage.Description);
                    }
                    return View(userModel);
                }
                ModelState.Clear();
                return RedirectToAction("ConfirmEmail", new { email = userModel.Email });
            }
            return View(userModel);
        }
        [Route("Signin")]
        public IActionResult Signin()
        {
            return View();
        }
        [Route("Signin")]
        [HttpPost]
        public async Task<IActionResult> Signin(SignInModel signInModel)
        {
            if (ModelState.IsValid)
            {
               var result=await _accountRepository.PasswordSignInAsync(signInModel);
               if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                if (result.IsNotAllowed)
                {
                    ModelState.AddModelError("", "Not Allowed to login");
                }
                else { ModelState.AddModelError("", "Invalid credentials"); }
                
            }
            return View(signInModel);
        }
        public async Task<IActionResult> Signout()
        {
            await _accountRepository.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        [Route("change-password")]
        public async Task<IActionResult> ChangePassword()
        {
            //await _accountRepository.SignOutAsync();
            return View();
        }
        [HttpPost("change-password")]
        public async Task<IActionResult> ChangePasswordAsync(ChangePasswordModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _accountRepository.ChangePasswordAsync(model);
                if (result.Succeeded)
                {
                    ViewBag.IsSuccess = true;
                    ModelState.Clear();
                    return View();
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);
        }
        [HttpGet("confirm-email")]
        [AllowAnonymous]
        public async Task<IActionResult> ConfirmEmail(string uid,string token,string email)
        {
            EmailConfirmModel model = new EmailConfirmModel
            {
                Email = email
            };
            
            if (!string.IsNullOrEmpty(uid) && !string.IsNullOrEmpty(token))
            {
                token = token.Replace(' ', '+');
                var result = await _accountRepository.ConfirmEmailAsync(uid, token);
                if (result.Succeeded)
                {
                    model.EmailVerified = true;
                }
            }
            /*if(uid==null || token == null)
            {
                return RedirectToAction("index", "home");
            }*/
            return View(model);
           
        }
        [HttpPost("confirm-email")]
        [AllowAnonymous]
        public async Task<IActionResult> ConfirmEmail(EmailConfirmModel model)
        {
            var user = await _accountRepository.GetUserByEmailAsync(model.Email);
            if (user != null)
            {
                if (user.EmailConfirmed)
                {
                    model.EmailVerified = true;
                    return View(model);
                }

                await _accountRepository.GenerateEmailConfirmationTokenAsync(user);
                model.EmailSent = true;
                ModelState.Clear();
            }
            else
            {
                ModelState.AddModelError("", "Something went wrong.");
            }
            return View(model);
        }
        [AllowAnonymous,HttpGet("forgot-password")]
        public IActionResult ForgotPassword()
        {
            return View();
        }
        [AllowAnonymous, HttpPost("forgot-password")]
        public async Task<IActionResult> ForgotPassword(ForgotPasswordModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _accountRepository.GetUserByEmailAsync(model.Email);
                if (user !=null)
                {
                    await _accountRepository.GenerateForgotPasswordTokenAsync(user);
                }
                ModelState.Clear();
                model.EmailSent = true;
            }
            return View(model);
        }
        [AllowAnonymous, HttpGet("reset-password")]
        public IActionResult ResetPassword(string uid, string token)
        {
            ResetPasswordModel resetPasswordModel = new ResetPasswordModel
            {
                Token = token,
                UserId = uid
            };
            return View(resetPasswordModel);
        }

        [AllowAnonymous, HttpPost("reset-password")]
        public async Task<IActionResult> ResetPassword(ResetPasswordModel model)
        {
            if (ModelState.IsValid)
            {
                model.Token = model.Token.Replace(' ', '+');
                var result = await _accountRepository.ResetPasswordAsync(model);
                if (result.Succeeded)
                {
                    ModelState.Clear();
                    model.IsSuccess = true;
                    return View(model);
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);
        }
        public IActionResult Profile()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Profile(UserProfileModel userProfile)
        {
            if (ModelState.IsValid)
            {
                var result = await _accountRepository.ChangeProfileDetail(userProfile);

                if (!result.Succeeded)
                {
                    foreach (var errorMessage in result.Errors)
                    {
                        ModelState.AddModelError("", errorMessage.Description);
                    }
                    return View(userProfile);
                }
                ModelState.Clear();
            }
            return View(userProfile);
        }


    }
}

HubbleSpace_Final-master/HubbleSpace_Final/Views/Client_Accounts/ChangePassword.cshtml
@model HubbleSpace_Final.Models.ChangePasswordModel

@{
    ViewData["Title"] = "Change password";
    Layout = "_FrontendLayout";
}
<div class="container" style="min-height: 400px;">
    <div class="row">
        <div class="col-lg-12">
            <!-- breadcrumb-->
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/../Home">Home</a></li>
                    <li aria-current="page" class="breadcrumb-item active">Change Password</li>
                </ol>
            </nav>
        </div>
        <div class="col-lg-12">
            <div class="box">
                <div class="col-md-12 offset-12">
                    <h1>Change Password</h1>
                    @if (ViewBag.IsSuccess == true)
                    {
                        <div class="alert alert-success" role="alert">
                            Password has been updated successfully
                        </div>
                    }
                    <form asp-action="ChangePassword">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="CurrentPassword" class="control-label"></label>
                            <input asp-for="CurrentPassword" class="form-control" />
                            <span asp-validation-for="CurrentPassword" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="NewPassword" class="control-label"></label>
                            <input asp-for="NewPassword" class="form-control" />
                            <span asp-validation-for="NewPassword" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ConfirmNewPassword" class="control-label"></label>
                            <input asp-for="ConfirmNewPassword" class="form-control" />
                            <span asp-validation-for="ConfirmNewPassword" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <a asp-controller="Home" asp-action="Index" class="btn btn-outline-secondary">Back</a>
                            <input type="submit" value="Change Password" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

HubbleSpace_Final-master/HubbleSpace_Final/Views/Client_Accounts/ConfirmEmail.cshtml
@model EmailConfirmModel

@{
    ViewData["Title"] = "Confirm email";
    Layout = "_FrontendLayout";
}

<div class="container" style="min-height: 400px;">
    <div class="row">
        <div class="col-lg-12">
            <!-- breadcrumb-->
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/../Home">Home</a></li>
                    <li aria-current="page" class="breadcrumb-item active">Confirm Email</li>
                </ol>
            </nav>
        </div>
        <div class="col-lg-12">
            <div class="box">
                <div class="col-md-12 offset-12">
                    @if (Model.EmailVerified == true)
                    {
                        <div class="alert alert-success" role="alert">
                            <p>Your email has been verified successfully.</p>
                        </div>
                        <a asp-controller="Client_Accounts" asp-action="Signin" class="btn btn-outline-secondary">Sign in</a>
                    }
                    else
                    {
                        if (Model.EmailSent)
                        {
                            <p>Email sent on your registered email id.</p>
                        }

                        else
                        {
                            <p>We have sent an email on your email id. Click on the link to login.</p>
                        }

                        <form asp-action="ConfirmEmail">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="Email" />

                            <p>Did not get any email of deleted by mistake?</p>
                            <div class="form-group">
                                <input type="submit" value="Resend confirmation email" class="btn btn-primary" />
                            </div>
                        </form>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

HubbleSpace_Final-master/HubbleSpace_Final/Views/Client_Accounts/ForgotPassword.cshtml
@model HubbleSpace_Final.Models.ForgotPasswordModel

@{
    ViewData["Title"] = "ForgotPassword";
    Layout = "_FrontendLayout";
}

<div class="container" style="min-height: 400px;">
    <div class="row">
        <div class="col-lg-12">
            <!-- breadcrumb-->
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/../Home">Home</a></li>
                    <li aria-current="page" class="breadcrumb-item active">Forgot Password</li>
                </ol>
            </nav>
        </div>
        <div class="col-lg-12">
            <div class="box">
                <div class="col-md-12 offset-12">
                    @if (Model?.EmailSent == true)
                    {
                        <div class="alert alert-success" role="alert">
                            <p>
                                If you are registered with us, <br />
                                We have sent an email on your registered email id
                            </p>
                            <a asp-controller="Client_Accounts" asp-action="Signin" class="btn btn-outline-secondary">Back to login</a>

                        </div>
                    }
                    else
                    {
                        <p>Forgot your password? Don't worry, you can reset it easily.</p>
                        <form action="/forgot-password" method="post">

                            <div class="form-group">
                                <label class="control-label" for="Email">Registered email address</label>
                                <input class="form-control" type="email" data-val="true" data-val-email="The Registered email address field is not a valid e-mail address." data-val-required="The Registered email address field is required." id="Email" name="Email" value="">
                                <span class="text-danger field-validation-valid" data-valmsg-for="Email" data-valmsg-replace="true"></span>
                            </div>

                            <div class="form-group">
                                <a asp-controller="Client_Accounts" asp-action="Signin" class="btn btn-outline-secondary">Sign in</a>
                                <input type="reset" value="Reset" class="btn btn-danger">
                                <input type="submit" value="Continue" class="btn btn-primary">
                            </div>
                            <input name="__RequestVerificationToken" type="hidden" value="CfDJ8MzNJpldWnZJvTU4fBkdJT8PBpznj0SAi7m-zFhmierch8Ifx0X_kv6z9kuOTq49N1sl8x_By7E8_DlbtZ2Y0eSqBwGq2MDBdb_3CI62346k1p5Yg43_wnClzRrPMQ-Hka60q8duVG83_lv1JeyDATQ">
                        </form>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

HubbleSpace_Final-master/HubbleSpace_Final/Views/Client_Accounts/Profile.cshtml
@model HubbleSpace_Final.Models.UserProfileModel
@inject Microsoft.AspNetCore.Identity.SignInManager<ApplicationUser> _signInManager
@inject Microsoft.AspNetCore.Identity.UserManager<ApplicationUser> _userManager

@{
    ViewData["Title"] = "Your profile";
    Layout = "_FrontendLayout";
}

<div class="container" style="min-height: 400px;">
    <div class="row">
        <div class="col-lg-12">
            <!-- breadcrumb-->
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/../Home">Home</a></li>
                    <li aria-current="page" class="breadcrumb-item active">Your Profile</li>
                </ol>
            </nav>
        </div>
        <div class="col-lg-12">
            <div class="box">
                <h1>Your Profile</h1>
                <form asp-action="Profile">
                    @if (_signInManager.IsSignedIn(User))
                    {

                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Username" class="control-label"></label>
                            <input asp-for="Username" value="@(User.FindFirst("Userusername").Value)" readonly="readonly" disabled="disabled" class="form-control" />
                            <span asp-validation-for="Username" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="FirstName" class="control-label"></label>
                            <input asp-for="FirstName" value="@(User.FindFirst("UserFirstName").Value)" class="form-control" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="LastName" class="control-label"></label>
                            <input asp-for="LastName" value="@(User.FindFirst("UserLastName").Value)" class="form-control" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="DOB" class="control-label"></label>

                            <input type="date" asp-for="DOB" value="@(User.FindFirst("UserDOB").Value)" class="form-control" />
                            <span asp-validation-for="DOB" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Email" class="control-label"></label>
                            <input asp-for="Email" value="@(User.FindFirst("UserEmail").Value)" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address" class="control-label"></label>
                            <input asp-for="Address" value="@(User.FindFirst("UserAddress").Value)" class="form-control" />

                            <span asp-validation-for="Address" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Phone" class="control-label"></label>
                            <input asp-for="Phone" value="@(User.FindFirst("UserPhoneNumber").Value)" class="form-control" />
                            <span asp-validation-for="Phone" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="CreditCard" class="control-label"></label>
                            <input asp-for="CreditCard" value="@(User.FindFirst("UserCreditCard").Value)" class="form-control" />
                            <span asp-validation-for="CreditCard" class="text-danger"></span>
                        </div>

                    }
                    <div class="form-group">
                        <a asp-controller="Home" asp-action="Index" class="btn btn-outline-secondary">Home</a>
                        <input type="reset" value="Reset" class="btn btn-danger">
                        <input type="submit" value="Save" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

HubbleSpace_Final-master/HubbleSpace_Final/Views/Client_Accounts/ResetPassword.cshtml
@model HubbleSpace_Final.Models.ResetPasswordModel

@{
    Layout = "_FrontendLayout";
    ViewData["Title"] = "ResetPassword";
}
<div class="container" style="min-height: 400px">
    <div class="row">
        <div class="col-lg-12">
            <!-- breadcrumb-->
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="~/../Home">Home</a></li>
                    <li aria-current="page" class="breadcrumb-item active">Reset Password</li>
                </ol>
            </nav>
        </div>
        <div class="col-lg-12">
            <div class="box">
                <div class="col-md-12 offset-12">
                    @if (Model?.IsSuccess == true)
                    {
                        <div class="alert alert-success" role="alert">
                            <p>
                                You have updated your password successfully.
                            </p>
                            <a asp-controller="Client_Accounts" asp-action="Signin" class="btn btn-outline-secondary">Sign in</a>
                        </div>
                    }
                    else
                    {
                        <form asp-action="ResetPassword">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="UserId" class="form-control" />
                            <input type="hidden" asp-for="Token" class="form-control" />
                            <div class="form-group">
                                <label asp-for="NewPassword" class="control-label"></label>
                                <input asp-for="NewPassword" class="form-control" />
                                <span asp-validation-for="NewPassword" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ConfirmNewPassword" class="control-label"></label>
                                <input asp-for="ConfirmNewPassword" class="form-control" />
                                <span asp-validation-for="ConfirmNewPassword" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Reset password" class="btn btn-primary" />
                                <a asp-controller="Client_Accounts" asp-action="Signin" class="btn btn-outline-secondary">Back to Sign in</a>
                            </div>
                        </form>
                    }

                </div>
            </div>
        </div>
    </div>
</div>

HubbleSpace_Final-master/HubbleSpace_Final/Views/Client_Accounts/SignUp.cshtml
@model HubbleSpace_Final.Models.SignUpUserModel

@{
    ViewData["Title"] = "Sign up";
    Layout = "_FrontendLayout";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <!-- breadcrumb-->
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="~/../Home">Home</a></li>
                    <li aria-current="page" class="breadcrumb-item active">Sign up</li>
                </ol>
            </nav>
        </div>
        <div class="col-lg-12">
            <div class="box">
                <h1>Sign up</h1>
                <p class="lead">Already our customer?</p>
                <hr>
                <form asp-action="SignUp">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Username" class="control-label"></label>
                        <input asp-for="Username" class="form-control" />
                        <span asp-validation-for="Username" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ConfirmPassword" class="control-label"></label>
                        <input asp-for="ConfirmPassword" class="form-control" />
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary"><i class="fa fa-user-md"></i> Register</button>
                        <p>Click <a asp-action="Login" asp-controller="Account">here</a> to login</p>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

HubbleSpace_Final-master/HubbleSpace_Final/Views/Client_Accounts/Signin.cshtml
@model HubbleSpace_Final.Models.SignInModel

@{
    ViewData["Title"] = "Sign in";
    Layout = "_FrontendLayout";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <!-- breadcrumb-->
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="~/../Home">Home</a></li>
                    <li aria-current="page" class="breadcrumb-item active">Sign in</li>
                </ol>
            </nav>
        </div>
        <div class="col-lg-12">
            <div class="box">
                <h1>Sign in</h1>
                <hr>
                <form asp-action="Signin">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Username" class="control-label"></label>
                        <input asp-for="Username" class="form-control" />
                        <span asp-validation-for="Username" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="RememberMe" /> @Html.DisplayNameFor(model => model.RememberMe)
                        </label>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary"><i class="fa fa-user-md"></i> Sign in</button>
                        <p><a asp-action="ForgotPassword" asp-controller="Client_Accounts">Forgot password?</a></p>
                        <p>Click <a asp-action="SignUp" asp-controller="Client_Accounts">here</a> to Sign Up</p>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>